git:
  pagers:
    - colorArg: always
      pager: 'delta --light --paging=never --features=gruvbox-material-light --line-numbers --hyperlinks --hyperlinks-file-link-format="idea://open?file={path}&line={line}"'

gui:
  showCommandLog: false
  theme:
    activeBorderColor:
      - "#6c782e"
      - bold
    inactiveBorderColor:
      - "#514036"
    searchingActiveBorderColor:
      - "#c35e0a"
      - bold
    optionsTextColor:
      - "#7c6f64"
    selectedLineBgColor:
      - "#e2cca9"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#7c6f64"
    cherryPickedCommitBgColor:
      - "#45707a"
    markedBaseCommitFgColor:
      - "#45707a"
    markedBaseCommitBgColor:
      - "#b47109"
    unstagedChangesColor:
      - "#c14a4a"
    defaultFgColor:
      - "#514036"
