git:
  pagers:
    - colorArg: always
      pager: 'delta --dark --paging=never --features=gruvbox-material-dark --line-numbers --hyperlinks --hyperlinks-file-link-format="idea://open?file={path}&line={line}"'

gui:
  showCommandLog: false
  theme:
    activeBorderColor:
      - "#a9b665"
      - bold
    inactiveBorderColor:
      - "#e2cca9"
    searchingActiveBorderColor:
      - "#e78a4e"
      - bold
    optionsTextColor:
      - "#928374"
    selectedLineBgColor:
      - "#504945"
    inactiveViewSelectedLineBgColor:
      - bold
    cherryPickedCommitFgColor:
      - "#928374"
    cherryPickedCommitBgColor:
      - "#7daea3"
    markedBaseCommitFgColor:
      - "#7daea3"
    markedBaseCommitBgColor:
      - "#d8a657"
    unstagedChangesColor:
      - "#ea6962"
    defaultFgColor:
      - "#e2cca9"
