[mgr]
# NOTE: can be combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

cwd = { fg = "#e2cca9", italic = true }

# Hovered
hovered         = { bg = "#f2e5bc" }
preview_hovered = { bg = "#f2e5bc" }

# Find
find_keyword  = { fg = "#fbf1c7", bg = "#c35e0a", bold = true }
find_position = { fg = "#4c7a5d", bg = "#f2e5bc", bold = true }

# Marker
marker_copied   = { fg = "#6c782e", bg = "#6c782e" }
marker_cut      = { fg = "#c14a4a", bg = "#c14a4a" }
marker_marked   = { fg = "#945e80", bg = "#945e80" }
marker_selected = { fg = "#45707a", bg = "#45707a" }

# Count
count_copied   = { fg = "#fbf1c7", bg = "#6c782e" }
count_cut      = { fg = "#fbf1c7", bg = "#c14a4a" }
count_selected = { fg = "#fbf1c7", bg = "#45707a" }

# Border
border_symbol = "│"
border_style  = { fg = "#4c7a5d" }

# Tab
[tabs]
active   = { fg = "#e2cca9", bg = "#45707a" }
inactive = { fg = "#45707a", bg = "#e2cca9" }

[mode]
normal_main = { fg = "#e2cca9", bg = "#45707a", bold = true }
normal_alt  = { fg = "#45707a", bg = "#e2cca9" }

select_main = { fg = "#e2cca9", bg = "#945e80", bold = true }
select_alt  = { fg = "#945e80", bg = "#e2cca9" }

unset_main  = { fg = "#e2cca9", bg = "#945e80", bold = true }
unset_alt   = { fg = "#945e80", bg = "#e2cca9" }

[status]
overall   = { fg = "#514036", bg = "#fbf1c7" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label  = { fg = "#514036", bold = true }
progress_normal = { fg = "#45707a", bg = "#f2e5bc" }
progress_error  = { fg = "#c14a4a", bg = "#f2e5bc" }

# Permissions
perm_type  = { fg = "#45707a" }
perm_read  = { fg = "#b47109" }
perm_write = { fg = "#c14a4a" }
perm_exec  = { fg = "#6c782e" }
perm_sep   = { fg = "#e2cca9" }

[pick]
border   = { fg = "#4c7a5d" }
active   = { fg = "#514036",  bg = "#f2e5bc" }
inactive = { fg = "#514036" }

# Input
[input]
border   = { fg = "#4c7a5d" }
title    = { fg = "#4c7a5d" }
value    = { fg = "#945e80" }
selected = { bg = "#f2e5bc" }

# Completion
[cmp]
border   = { fg = "#4c7a5d" }
active   = { fg = "#514036", bg = "#e2cca9" }
inactive = { fg = "#514036" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#4c7a5d" }
title   = { fg = "#4c7a5d" }
hovered = { fg = "#514036", bg = "#f2e5bc" }

# Which
[which]
cols            = 3
mask            = { bg = "#fbf1c7" }
cand            = { fg = "#45707a" }
rest            = { fg = "#45707a" }
desc            = { fg = "#945e80" }
separator       = " ➜ "
separator_style = { fg = "#7c6f64" }

# Confirm
[confirm]
border  = { fg = "#4c7a5d" }
title   = { fg = "#4c7a5d" }
content = {}
list    = {}
btn_yes = { bg = "#f2e5bc" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#4c7a5d" }
title   = { fg = "#4c7a5d" }

# Notify
[notify]
title_info  = { fg = "#4c7a5d" }
title_warn  = { fg = "#b47109" }
title_error = { fg = "#c14a4a" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#6c782e" }
run     = { fg = "#945e80" }
desc    = { fg = "#45707a" }
hovered = { bg = "#f2e5bc" }
footer  = { fg = "#514036", bg = "#f9f5d7" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#b47109" },

	# Media
	{ mime = "{audio,video}/*", fg = "#945e80" },

	# Archives
	{ mime = "application/*zip", fg = "#c14a4a" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#c14a4a" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#45707a" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#c14a4a" },

	# Special files
	{ name = "*", is = "orphan", bg = "#c14a4a" },
	{ name = "*", is = "exec"  , fg = "#6c782e" },

	# Fallback
	{ name = "*/", fg = "#45707a" },
	{ name = "*", fg = "#514036" }
]
    