[mgr]
# NOTE: can be combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

cwd = { fg = "#e2cca9", italic = true }

# Hovered
hovered         = { bg = "#514036" }
preview_hovered = { bg = "#514036" }

# Find
find_keyword  = { fg = "#1d2021", bg = "#e78a4e", bold = true }
find_position = { fg = "#89b482", bg = "#514036", bold = true }

# Marker
marker_copied   = { fg = "#a9b665", bg = "#a9b665" }
marker_cut      = { fg = "#ea6962", bg = "#ea6962" }
marker_marked   = { fg = "#d3869b", bg = "#d3869b" }
marker_selected = { fg = "#7daea3", bg = "#7daea3" }

# Count
count_copied   = { fg = "#1d2021", bg = "#a9b665" }
count_cut      = { fg = "#1d2021", bg = "#ea6962" }
count_selected = { fg = "#1d2021", bg = "#7daea3" }

# Border
border_symbol = "│"
border_style  = { fg = "#89b482" }

# Tab
[tabs]
active   = { fg = "#1d2021", bg = "#7daea3" }
inactive = { fg = "#7daea3", bg = "#504945" }

[mode]
normal_main = { fg = "#1d2021", bg = "#7daea3", bold = true }
normal_alt  = { fg = "#7daea3", bg = "#504945" }

select_main = { fg = "#1d2021", bg = "#d3869b", bold = true }
select_alt  = { fg = "#d3869b", bg = "#504945" }

unset_main  = { fg = "#1d2021", bg = "#d3869b", bold = true }
unset_alt   = { fg = "#d3869b", bg = "#504945" }

[status]
overall   = { fg = "#e2cca9", bg = "#1d2021" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label  = { fg = "#e2cca9", bold = true }
progress_normal = { fg = "#7daea3", bg = "#514036" }
progress_error  = { fg = "#ea6962", bg = "#514036" }

# Permissions
perm_type  = { fg = "#7daea3" }
perm_read  = { fg = "#d8a657" }
perm_write = { fg = "#ea6962" }
perm_exec  = { fg = "#a9b665" }
perm_sep   = { fg = "#504945" }

[pick]
border   = { fg = "#89b482" }
active   = { fg = "#e2cca9",  bg = "#504945" }
inactive = { fg = "#e2cca9" }

# Input
[input]
border   = { fg = "#89b482" }
title    = { fg = "#89b482" }
value    = { fg = "#d3869b" }
selected = { bg = "#504945" }

# Completion
[cmp]
border   = { fg = "#89b482" }
active   = { fg = "#e2cca9", bg = "#504945" }
inactive = { fg = "#e2cca9" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#89b482" }
title   = { fg = "#89b482" }
hovered = { fg = "#e2cca9", bg = "#504945" }

# Which
[which]
cols            = 3
mask            = { bg = "#1d2021" }
cand            = { fg = "#7daea3" }
rest            = { fg = "#7daea3" }
desc            = { fg = "#d3869b" }
separator       = " ➜ "
separator_style = { fg = "#928374" }

# Confirm
[confirm]
border  = { fg = "#89b482" }
title   = { fg = "#89b482" }
content = {}
list    = {}
btn_yes = { bg = "#504945" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#89b482" }
title   = { fg = "#89b482" }

# Notify
[notify]
title_info  = { fg = "#89b482" }
title_warn  = { fg = "#d8a657" }
title_error = { fg = "#ea6962" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#a9b665" }
run     = { fg = "#d3869b" }
desc    = { fg = "#7daea3" }
hovered = { bg = "#514036" }
footer  = { fg = "#e2cca9", bg = "#1d2021" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#d8a657" },

	# Media
	{ mime = "{audio,video}/*", fg = "#d3869b" },

	# Archives
	{ mime = "application/*zip", fg = "#ea6962" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#ea6962" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#7daea3" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#ea6962" },

	# Special files
	{ name = "*", is = "orphan", bg = "#ea6962" },
	{ name = "*", is = "exec"  , fg = "#a9b665" },

	# Fallback
	{ name = "*/", fg = "#7daea3" },
	{ name = "*", fg = "#e2cca9" }
]
    