[style.command_name]
foreground = { rgb = { r = 3, g = 106, b = 150 } }

[style.example_text]
foreground = { rgb = { r = 108, g = 102, b = 75 } }

[style.example_code]
foreground = { rgb = { r = 132, g = 110, b = 21 } }

[style.example_variable]
foreground = { rgb = { r = 163, g = 20, b = 77 } }
