[style.command_name]
foreground = { rgb = { r = 226, g = 204, b = 169 } }

[style.example_text]
foreground = { rgb = { r = 146, g = 131, b = 116 } }

[style.example_code]
foreground = { rgb = { r = 169, g = 182, b = 101 } }

[style.example_variable]
foreground = { rgb = { r = 216, g = 166, b = 87 } }
