onboarding = false

[keys]
focus_pane_left = ["prefix+j", "alt+j"]
focus_pane_down = ["prefix+k", "alt+k"]
focus_pane_up = ["prefix+l", "alt+l"]
focus_pane_right = ["prefix+;", "alt+;"]

navigate_pane_left = "j"
navigate_pane_down = "k"
navigate_pane_up = "l"
navigate_pane_right = ";"

swap_pane_left = "prefix+shift+j"
swap_pane_down = "prefix+shift+k"
swap_pane_up = "prefix+shift+l"
swap_pane_right = "prefix+shift+;"

switch_workspace = "alt+1..9"

[theme]
auto_switch = true
dark_name = "dracula"
light_name = "rose-pine-dawn"

[ui]
hide_tab_bar_when_single_tab = true
sidebar_width = 24
